name: international_phone_field
description: A Flutter package for international phone field
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'


dependencies:

  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  mask_text_input_formatter: ^2.9.0
  formz: ^0.7.0

  cupertino_icons: ^1.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flags/